before_install:
- gem install bundler -v 2.0.1
script:
- bundle install
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: jekyll-dash
  on:
    tags: true
    repo: bitbrain/jekyll-dash
