title: Woong's Blog
author: Woong
email: woongchoi84@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  I'm a Creep; I'm a Weirdo.
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
show_excerpts: false # set to true to show excerpts on the homepage

url: https://woongchoi84.github.io

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag


# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: woongchoi84

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/woongchoi84
      icon: twitter-square
      color: cyan
    - url: https://github.com/woongchoi84
      icon: github-square
      color: purple

authors:
    gravatar: 4a8702b1bdf3853f2fd5d4442bb4a199

# Build settings
remote_theme: jekyll-dash

plugins:
 - jekyll-sitemap
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
